Xulei/brb feature feedback setting
Azure-Samples/communication-services-web-chat-hero pull request #27
Opened 2021-07-05 19:38 UTC by lei-msft

## Purpose

* Adds Feedback setting
* Adjusts Feedback button in the header
* RModifies utils codes

**1. Feedback enabled**
![chatapp_feedback_enabled](https://user-images.githubusercontent.com/86329602/124512573-91bad580-dd8d-11eb-954d-5961ded22677.png)
**2. Feedback disabled**
![chatapp_feedback_disabled](https://user-images.githubusercontent.com/86329602/124512584-97182000-dd8d-11eb-81b3-71dc3cea8c9b.png)

## Does this introduce a breaking change?

```
[ ] Yes
[X] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

**Feedback Setting**

```
[ ] Bugfix
[X] Feature
[ ] Code style update (formatting, local variables)
[X] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

* Test the code

```
```

## What to Check
Verify that the following are valid
* ...

## Other Information

2021-07-05 20:07 UTC, alkwa-msft commented on Chat/ClientApp/src/components/FeedbackButton.tsx
> +          <TooltipHost
In the calling app if we have the space we will use the Report a Bug text.

https://github.com/Azure-Samples/communication-services-web-calling-hero/blob/public-preview/Calling/ClientApp/src/components/Header.tsx

![image](https://user-images.githubusercontent.com/79329532/124514472-f5470200-dd91-11eb-9bbd-e03d711d955e.png)

2021-07-05 20:08 UTC, alkwa-msft requested changes
I think we want to potentially keep the report a bug text. Can we do something similar to what calling has done? For a desktop view it shows the text. if it doesnt have as much space it cuts out the text?

2021-07-06 02:18 UTC, lei-msft commented
> I think we want to potentially keep the report a bug text. Can we do something similar to what calling has done? For a desktop view it shows the text. if it doesnt have as much space it cuts out the text?

Good point ~~~~ Thx a lot

1. Show the report a bug text
![feedback_button_with_text](https://user-images.githubusercontent.com/86329602/124532571-ac10a580-ddc5-11eb-9629-a51d23b41b14.png)

2. Hide the report a bug text
![feedback_button_icon_only](https://user-images.githubusercontent.com/86329602/124532577-af0b9600-ddc5-11eb-8de4-f39f375153b3.png)

2021-07-06 18:25 UTC, alkwa-msft approved these changes

2021-07-06 18:25 UTC, merged